# Generated by Django 3.2.7 on 2023-10-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={},
        ),
    ]
